name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  google_fonts: ^8.0.0
  shared_preferences: ^2.5.4
  flutter_gen: ^5.12.0
  flutter_svg: ^2.2.3
  flutter_screenutil: ^5.9.3
  fvm: ^4.0.5
  equatable: ^2.0.8
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/gen/
  line_length: 80
  
  integrations:
    flutter_svg: false
    lottie: false
